databases:
  - name: search_engine
    databaseName: search_engine
    user: search_engine
    plan: free

services:
  - type: web
    name: search_engine
    runtime: ruby
    plan: free
    buildCommand: "./bin/render-build.sh"
    
    startCommand: "bundle exec rails server"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: search_engine
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false
      - key: WEB_CONCURRENCY
        value: 2